name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Build dengan Buildozer
        uses: ArtemSBulgakov/buildozer-action@v3
        id: buildozer
        with:
          command: buildozer android debug
          repository_root: .

      - name: Buat Rilis APK
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*.apk
          tag_name: v1.0-${{ github.run_number }}
          name: Notepad Super v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
